---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hokusai-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hokusai-demo
      name: hokusai-demo
      namespace: default
    spec:
      containers:
      - env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: hokusai-demo-config
              key: RAILS_ENV
        - name: FOO_CONFIG
          valueFrom:
            configMapKeyRef:
              name: hokusai-demo-config
              key: FOO_CONFIG
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: hokusai-demo-secrets
              key: SECRET_KEY_BASE
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hokusai-demo-secrets
              key: DATABASE_URL
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/hokusai-demo:staging
        imagePullPolicy: Always
        name: hokusai-demo
        command: ['bundle', 'exec', 'puma']
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hokusai-demo
  name: hokusai-demo
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2016-01-19_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 80
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: hokusai-demo
  sessionAffinity: None
  type: LoadBalancer
